---
- hosts: all
  any_errors_fatal: true
  gather_facts: false
  roles:
    - bootstrap-os
  tags:
    - bootstrap-os


- hosts: all
  any_errors_fatal: true
  gather_facts: true

- hosts: all:!network-storage
  any_errors_fatal: true
  vars:
    - dns_server: ''
  roles:
    - { role: kubernetes/preinstall, tags: [bootstrap-os, resolvconf] }
    - { role: docker, tags: docker }

- hosts: etcd:!k8s-cluster
  any_errors_fatal: true
  roles:
    - { role: etcd, tags: etcd }

- hosts: k8s-cluster
  any_errors_fatal: true
  roles:
    - { role: etcd, tags: etcd }
    - { role: kubernetes/node, tags: node }
    - { role: network_plugin, tags: network }

- hosts: kube-master
  any_errors_fatal: true
  roles:
    - { role: kubernetes/master, tags: master }
    - { role: kubernetes-apps/lib, tags: apps }
    - { role: kubernetes-apps/network_plugin, tags: network }

- hosts: k8s-cluster
  any_errors_fatal: true
  roles:
    - { role: dnsmasq, tags: dnsmasq }

- hosts: kube-master[0]
  any_errors_fatal: true
  roles:
    - { role: kubernetes-apps/lib, tags: apps }
    - { role: kubernetes-apps, tags: apps }

- hosts: all:!network-storage
  any_errors_fatal: true
  roles:
    - { role: kubernetes/preinstall, tags: resolvconf }
