---
- name: Configure | Check if member is in cluster
  shell: "{{ bin_dir }}/etcdctl --no-sync --peers={{ etcd_access_addresses }} member list | grep -q {{ etcd_access_address }}"
  register: etcd_member_in_cluster
  ignore_errors: true
  changed_when: false
  when: is_etcd_master
  tags: facts

- name: Configure | Add member to the cluster if it is not there
  when: is_etcd_master and etcd_member_in_cluster.rc != 0 and etcd_cluster_is_healthy.rc == 0
  shell: "{{ bin_dir }}/etcdctl --peers={{ etcd_access_addresses }} member add {{ etcd_member_name }} {{ etcd_peer_url }}"

- name: Configure | Copy etcd.service systemd file
  template:
    src: "etcd-{{ etcd_deployment_type }}.service.j2"
    dest: /etc/systemd/system/etcd.service
    backup: yes
  when: ansible_service_mgr == "systemd" and is_etcd_master
  notify: restart etcd

- name: Configure | Write etcd initd script
  template:
    src: "deb-etcd-{{ etcd_deployment_type }}.initd.j2"
    dest: /etc/init.d/etcd
    owner: root
    mode: 0755
  when: ansible_service_mgr in ["sysvinit","upstart"] and ansible_os_family == "Debian" and is_etcd_master
  notify: restart etcd
