---
- include: pre_upgrade.yml
  tags: etcd-pre-upgrade
- include: check_certs.yml
  tags: [etcd-secrets, facts]
- include: gen_certs.yml
  tags: etcd-secrets
- include: install.yml
  when: is_etcd_master
  tags: upgrade
- include: set_cluster_health.yml
  when: is_etcd_master
- include: configure.yml
  when: is_etcd_master
- include: refresh_config.yml
  when: is_etcd_master

- name: Ensure etcd is running
  service:
    name: etcd
    state: started
    enabled: yes
  when: is_etcd_master

- name: Restart etcd if binary changed
  command: /bin/true
  notify: restart etcd
  when: etcd_deployment_type == "host" and etcd_copy.stdout_lines and is_etcd_master

# Reload systemd before starting service
- meta: flush_handlers

# After etcd cluster is assembled, make sure that
# initial state of the cluster is in `existing`
# state insted of `new`.
- include: set_cluster_health.yml
  when: is_etcd_master
- include: refresh_config.yml
  when: is_etcd_master
